title: Portfólio
author: CoutoDev
email: c.svitor@yahoo.com.br
description: > # this means to ignore newlines until "baseurl:"
  Portifólio de Vitor Coutinho Fernandes

theme: minima
# social links
twitter_username: CoutoDev # DO NOT include the @ character, or else the build will fail!
github_username:  CoutoDev # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
